FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# COPY ./package.json ./
COPY --chown=node:node package.json .
RUN npm install 
# COPY . .
COPY --chown=node:node . .


CMD ["npm","run","start"]

# b14058d3f6d96bae30569568ccd81079ed1daac39c90df253d4cb1a060c02abd