FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .
# The chown command stands for "change owner" and the -R flag stands for "recursive", meaning 
# that the command will change the owner of the /app directory and all its contents. 
# The node user is a non-root user created by the Node.js Docker image, and is commonly 
# used as the user to run Node.js applications in Docker containers.
RUN chown -R node /app

USER node

CMD ["npm","run","start"]

# bc04214b13b1572354550aae80ff0df6de8dd1f10b9656f00f0df7c41bcf8acd