apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    # this calls the server-deployment file
    component: server
  ports:
    - port: 5000
      targetPort: 5000