FROM node:14.14.0-alpine
WORKDIR "/app"

COPY ./package.json ./
# COPY --chown=node:node package.json .
RUN npm install 

COPY . .
# COPY --chown=node:node . .
# USER node

CMD ["npm", "run", "dev"]

# 45898b9d2b93753ffad52c98de46d89ab1f115a0a334965e54d8286c592c9724