FROM node:14.14.0-alpine
WORKDIR "/app"

COPY ./package.json ./
# COPY --chown=node:node package.json .
RUN npm install 

COPY . .
# COPY --chown=node:node . .
# USER node

CMD ["npm", "run", "dev"]

# 7812f8c42900813454267938827ac6cc62feaadc910165e8ed8b240ea792f8dd 